// <auto-generated />
using System;
using CityBusManagement.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityBusManagement.DAL.Migrations
{
    [DbContext(typeof(RouteDetailsDbContext))]
    [Migration("20220206153937_employee")]
    partial class employee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityBusManagement.Entity.Models.BusDetails", b =>
                {
                    b.Property<int>("busNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("arrivalTime")
                        .HasColumnType("int");

                    b.Property<string>("busName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("busNo");

                    b.ToTable("busdetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.BusStop", b =>
                {
                    b.Property<int>("busStopNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("arrivalTime")
                        .HasColumnType("int");

                    b.Property<int>("depatureTime")
                        .HasColumnType("int");

                    b.Property<string>("stopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("busStopNo");

                    b.ToTable("busstop");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.Employee", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("empName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tripDetailstripId")
                        .HasColumnType("int");

                    b.HasKey("empId");

                    b.HasIndex("tripDetailstripId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.RouteDetails", b =>
                {
                    b.Property<int>("routeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("busStopNo")
                        .HasColumnType("int");

                    b.Property<string>("destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("routeNo");

                    b.HasIndex("busStopNo");

                    b.ToTable("routedetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.Trip", b =>
                {
                    b.Property<int>("tripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("busDetailsbusNo")
                        .HasColumnType("int");

                    b.Property<int?>("routeDetailsrouteNo")
                        .HasColumnType("int");

                    b.Property<int>("tripCount")
                        .HasColumnType("int");

                    b.HasKey("tripId");

                    b.HasIndex("busDetailsbusNo");

                    b.HasIndex("routeDetailsrouteNo");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.Employee", b =>
                {
                    b.HasOne("CityBusManagement.Entity.Models.Trip", "tripDetails")
                        .WithMany("employeeDetails")
                        .HasForeignKey("tripDetailstripId");

                    b.Navigation("tripDetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.RouteDetails", b =>
                {
                    b.HasOne("CityBusManagement.Entity.Models.BusStop", null)
                        .WithMany("routeDetails")
                        .HasForeignKey("busStopNo");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.Trip", b =>
                {
                    b.HasOne("CityBusManagement.Entity.Models.BusDetails", "busDetails")
                        .WithMany("trip")
                        .HasForeignKey("busDetailsbusNo");

                    b.HasOne("CityBusManagement.Entity.Models.RouteDetails", "routeDetails")
                        .WithMany()
                        .HasForeignKey("routeDetailsrouteNo");

                    b.Navigation("busDetails");

                    b.Navigation("routeDetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.BusDetails", b =>
                {
                    b.Navigation("trip");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.BusStop", b =>
                {
                    b.Navigation("routeDetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.Trip", b =>
                {
                    b.Navigation("employeeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
