// <auto-generated />
using CityBusManagement.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityBusManagement.DAL.Migrations
{
    [DbContext(typeof(RouteDetailsDbContext))]
    [Migration("20220204183455_addedbusDetails")]
    partial class addedbusDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityBusManagement.Entity.Models.BusDetails", b =>
                {
                    b.Property<int>("BusNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("routeno")
                        .HasColumnType("int");

                    b.HasKey("BusNo");

                    b.ToTable("busDetails");
                });

            modelBuilder.Entity("CityBusManagement.Entity.Models.RouteDetails", b =>
                {
                    b.Property<int>("routeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("routeNo");

                    b.ToTable("RouteDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
